# Generated by Django 3.0.5 on 2020-05-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockName', models.CharField(max_length=100)),
                ('stockSymbol', models.CharField(max_length=7)),
                ('candle_pattern', models.CharField(choices=[('bumar', 'bullish marabozu'), ('bemar', 'bearish marabozu'), ('st', 'spinning top'), ('d', 'doji'), ('behar', 'bearish harami'), ('beeng', 'bearish engulfing'), ('bueng', 'bullish engulfing'), ('buhar', 'bullish harami'), ('dcc', 'dark cloud cover'), ('es', 'evening star'), ('h', 'hammer'), ('hm', 'hanging man'), ('ms', 'morning star'), ('pp', 'piercing pattern'), ('ss', 'shooting star'), ('na', 'none')], default='na', help_text='Candle Pattern', max_length=5)),
                ('candle_trend', models.CharField(choices=[('be', 'bearish'), ('bu', 'bullish'), ('na', 'none')], default='na', max_length=2)),
                ('s_and_r_trend', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=2)),
                ('volume', models.CharField(max_length=20, null=True)),
                ('volume_trend', models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='n', max_length=1)),
                ('macd_trend', models.CharField(choices=[('be', 'bearish'), ('bu', 'bullish'), ('na', 'none')], default='na', max_length=2)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
    ]
